# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  realweb:
    image: realweb
    build:
      context: .
      dockerfile: server/Real.Web/Dockerfile
    ports:
      - 5000:5000
